apiVersion: v1
kind: Pod
metadata:
  name: "flexvolume-digitalocean"
spec:
  containers:
    - name: "nginx"
      image: "nginx"
      ports:
        - name: "http"
          containerPort: 80
      volumeMounts:
        - name: "flexvolume"
          mountPath: "/data"
  volumes:
    - name: "flexvolume"
      flexVolume:
        driver: "pharmer/flexvolumes"
        fsType: "ext4"
        options:
          volumeId: "vol-id"